### ISSUE TITLE
ReferenceError: exports is not defined When migrated to version 3.0.0

### ISSUE THREAD

**Issue by AkramIsmail** [ticlo/rc-dock#62] opened 2021-01-19 15:06 UTC
ReferenceError: exports is not defined
Module../node_modules/rc-new-window/es/index.js

  12 |   };
  13 | };
  14 | 
> 15 | Object.defineProperty(exports, "__esModule", {
  16 |   value: true
  17 | });
  18 | 

I'm building a ReactJS application created using npx create -react-app, after updating the version of rc-dock from 2.6.2 to 3.0.0 the above error occured. I've tried many solution for this error but non has worked.

Thank you in advance.

**Comment by rinick** [comment] 2021-01-19 16:38
It works for me
could you create a sample project to reproduce this issue?

**Comment by AkramIsmail** [comment] 2021-01-23 14:37
![akram-git](https://user-images.githubusercontent.com/30923189/105581342-35906600-5d98-11eb-9487-e728679dddc4.PNG)
![akram-git-1](https://user-images.githubusercontent.com/30923189/105582002-65d80480-5d98-11eb-980e-18065f2ead19.PNG)

Dear I have a created a new project using 'npx create-react-app test-rc-dock', installed rc-dock using 'npm i --save rc-dock', then imported rc-dock using 'import DockLayout from 'rc-dock' ', implemented the same example as defined in the documentation I'm getting the same issue as defined previously in the above comment. Please check screenshots appended.

Any help is appreciated,
Thank you

**Comment by rinick** [comment] 2021-01-23 22:04
fixed in 3.0.1

**Closed** 2021-01-23 22:03 UTC
